CREATE TABLE CATEGORY(
ID INT  PRIMARY KEY,
NAME NVARCHAR(100) ,
Status TINYINT ,
CREATEDATE DATETIME ,
Image VARCHAR(100) ,
DESCRIPTION NVARCHAR(350) 
)
GO

CREATE TABLE PRODUCT(
ID INT  PRIMARY KEY,
NAME NVARCHAR(100) ,
Price Float ,
SalePrice Float ,
Status TINYINT ,
CATEGORYID INT  FOREIGN KEY (ID) REFERENCES CATEGORY(ID),
CREATEDATE DATETIME ,
Image VARCHAR(100) ,
DESCRIPTION NVARCHAR(350) ,
)
GO

CREATE TABLE BANNER(
ID INT  PRIMARY KEY,
NAME NVARCHAR(100) ,
Status TINYINT ,
Prioty int ,
CREATEDATE DATETIME ,
Image VARCHAR(100) ,
DESCRIPTION NVARCHAR(350) ,
)
GO
CREATE TABLE BLOG(
ID INT  PRIMARY KEY,
NAME NVARCHAR(100) ,
Status TINYINT ,
CREATEDATE DATETIME ,
Image VARCHAR(100) ,
DESCRIPTION NVARCHAR(350) ,
)
GO